### ISSUE TITLE
Question About Design and Implementation of a single core RISC-V CentralProcessing Unit

### ISSUE THREAD

**Issue by Barban09** [NikosDelijohn/RISCV-32I#4]
Hi, Nikos

I am looking foward to do my Work Degree about the Test of a version of RISCV and many other elements, so I after many hours searching online, your work really got my attention so I decided to download your code and run it on Quartus.

It is working, but when I was looking the part of the tests I got lost. After reading the file "Documentation.pdf" you mention that you used a toolchain found on the RISC-V repossitory in GitHub to ,I think, generate the assembly and machine code so the test can be completed, but I didnt find it so far. My question here is, That toolchain was a compiler? or any software that can be found in this repossitory? jaja and hopefully can you give me the name of that tool.

Oh I forgot one thing, for doing these tests you generate the .hex file and .dumpfile. So my question here is, Do you enter manually the data to ModelSim? or How do you manage to enter the .mif file to yout processor? 

I hope you can understand me and you can give some help with my questions,
Thanks a lot.

**Comment by NikosDelijohn** [comment]
Good day mate! I am happy that you find interest in this work of mine. It really means a lot to me. So anyway, let us get down to business. 
### [1]
> "...you mention that you used a toolchain found on the RISC-V repository..."

This is correct. The tests (whose hex & dumpfiles can be found under the Tests directory) were taken directly from the toolchain created from the **B**erkeley **A**rchitecture **R**esearch laboratory. More information can be found at:

- [BAR's RISC-V webpage](https://bar.eecs.berkeley.edu/projects/riscv.html)
- [riscv-gnu-toolchain repository](https://github.com/riscv/riscv-gnu-toolchain/)

### [2]
> "...Oh I forgot one thing, for doing these tests you generate the .hex file and .dumpfile. So my question here is, Do you enter manually the data to ModelSim? or How do you manage to enter the .mif file to your processor?..."

Once again, under the Test directory, you can find a python script (hex_to_mif.py). This is solely responsible for generating the memory initialization files for every test. Then this file is MANUALLY(!) inserted to ModelSIM for simulation. To answer directly your question: No, I do not attach the .mif file in some module of the pipeline.

I hope that you will find this information useful. 
Best Regards

**Comment by NikosDelijohn** [comment]
Hello again. Since I got no response from my previous comment I assume that your questions were answered. Feel free to contact me again if something comes up.
